version: '2'
services:
  firebird:
    image: 'dcms/firebird-docker:3.0.7-test'
    restart: always
    ports:
      - '3060:3060'
      - '3061:3061'
    environment:
      - 'SYSDBAPASS=x'
      - 'FIREBIRD_PORT=3060'
      - 'REMOTE_AUX_PORT=3061'
    volumes:
      - './testdb:/db'
