version: '2'
services:
  firebird:
    image: 'dcms/firebird-docker:stable'
    restart: always
    ports:
      - '3050:3050'
      - '3051:3051'
    environment:
      - 'SYSDBAPASS=masterkey'
      - 'FIREBIRD_PORT=3050'
      - 'REMOTE_AUX_PORT=3051'
    volumes:
      - '/kunden/GMSTest:/db'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
