version: '2'
services:
  fb256:
    image: 'dcms/firebird-docker:2.5.6'
    ports:
     - '3256:3050'
    extends:
     file: base.yml
     service: base

  fb257:
    image: 'dcms/firebird-docker:2.5.7'
    ports:
     - '3257:3050'
    extends:
     file: base.yml
     service: base

  fb258:
    image: 'dcms/firebird-docker:2.5.8'
    ports:
     - '3258:3050'
    extends:
     file: base.yml
     service: base

  fb300:
    image: 'dcms/firebird-docker:3.0.0'
    ports:
     - '3300:3050'
    extends:
     file: base.yml
     service: base

  fb303:
    image: 'dcms/firebird-docker:3.0.3'
    ports:
     - '3303:3050'
    extends:
     file: base.yml
     service: base

  fb400:
    image: 'dcms/firebird-docker:4.0.0Alpha'
    ports:
     - '3400:3050'
    extends:
     file: base.yml
     service: base
